export const LOAD_KUBE_CONTEXT = 'LOAD_KUBE_CONTEXT';
export const SET_KUBE_CONTEXT_WITH_CLUSTERS = 'SET_KUBE_CONTEXT_WITH_CLUSTERS';

export const GET_NAMESPACES = 'GET_NAMESPACES';
export const SET_NAMESPACES = 'SET_NAMESPACES';

export const GET_PODS = 'GET_PODS';
export const SET_PODS = 'SET_PODS';
